name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-ci:
    uses: faridlamaul/ci-template/.github/workflows/go-ci.yml@main
    with:
      go_version: "stable"
      run_lint: false # can enable once golangci-lint is configured in repo
      run_tests: true
      run_build: true
      build_output: "bin/omp-cost"
      build_package: "./cmd/omp-cost"
